/* eslint-disable @typescript-eslint/ban-ts-comment */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// @ts-ignore
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};














export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: "wordlepainter",
    storageBucket: "wordlepainter.firebasestorage.app",
    messagingSenderId: "750179707644",
    appId: process.env.FIREBASE_APPID,
    measurementId: process.env.FIREBASE_MEASUREMENT_ID
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
